### ISSUE TITLE
Update parsers dependencies (afm and uvl)

### ISSUE THREAD

**Issue by jagalindo** [flamapy/fm_metamodel#57]
New versions have arrised in pypi for the uvl parser and the afm parsers. We should make sure that this is up to date in all plugins setups and requirements

**Comment by jagalindo** [comment]
I'm reopening this. after the changes, now the uvl parser doesn't work

**Comment by jagalindo** [comment]
This is the error I'm finding now. For some reason, it looks for the wrong file
Traceback (most recent call last):
  File "/home/jagalindo/Repositorios/flama/test.py", line 3, in <module>
    result = dm.use_operation_from_file('ValidConfiguration', './data.uvl') # This launch the operation and stores the result on the result variable
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/famapy/core/discover.py", line 183, in use_operation_from_file
    vm_temp = self.__transform_to_model_from_file(file)
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/famapy/core/discover.py", line 211, in __transform_to_model_from_file
    return t2m(file).transform()
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/famapy/metamodels/fm_metamodel/transformations/uvl_reader.py", line 61, in transform
    self.read_imports()
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/famapy/metamodels/fm_metamodel/transformations/uvl_reader.py", line 97, in read_imports
    self.parse_import(import_node)
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/famapy/metamodels/fm_metamodel/transformations/uvl_reader.py", line 112, in parse_import
    uvl_transformation.transform()
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/famapy/metamodels/fm_metamodel/transformations/uvl_reader.py", line 38, in transform
    self.set_parse_tree()
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/famapy/metamodels/fm_metamodel/transformations/uvl_reader.py", line 35, in set_parse_tree
    self.parse_tree = get_tree(absolute_path)
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/uvlparser/main.py", line 7, in get_tree
    input_stream = FileStream(argv)
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/antlr4/FileStream.py", line 20, in __init__
    super().__init__(self.readDataFrom(fileName, encoding, errors))
  File "/home/jagalindo/Repositorios/flama/core/env/lib/python3.9/site-packages/antlr4/FileStream.py", line 25, in readDataFrom
    with open(fileName, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jagalindo/Repositorios/flama/FileSystem.uvl'

**Comment by jagalindo** [comment]
Updated in the last release
